[package]
name = "utm"
version = "0.1.2"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]
description = "Convert latitudes and longitudes to UTM coordinates"
license = "MIT"
homepage = "https://github.com/gadomski/utm"
repository = "https://github.com/gadomski/utm"
documentation = "http://gadomski.github.io/utm"
keywords = ["utm", "gis", "no_std"]

[dependencies]
num = {version = "0.3.0", default-features = false, optional = true}

[features]
no_std = ["num"]